Shop3T/E_shop/E_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/', views.Master, name='master'),
    path('', views.Index, name='index'),

    path('signup', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),

    #addtocart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),

    #Contact Page
    path('contact_us', views.Contact_Page, name = "contact_page"),

    #Cehckout page
    path('checkout/', views.CheckOut, name="checkout"),

    #Order page
    path('order/', views.Your_Order, name="order"),

    #Product page
    path('product/', views.Product_page, name="product"),

    #Product detail
    path('product/<str:id>',views.Product_Detail, name="product_detail"),

    #search
    path('search/', views.Search, name="search"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Shop3T/E_shop/store_app/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
import datetime

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Sub_Category(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    Availability =(('In Stock', 'In Stock'),('Out of Stock','Out of Stock'))

    category = models.ForeignKey(Category, on_delete=models.CASCADE,null=False,default='')
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE,null=False,default='')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE,null=True)
    image = models.ImageField(upload_to='ecommerce/pimg')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    Availability =models.CharField(choices=Availability, null =True,max_length=100)
    date = models.DateField(auto_now_add=True)
    desc = models.TextField(default="Will be updated soon")

    def __str__(self):
        return self.name

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email', error_messages={'exists': 'This Already Exists'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            return forms.ValidationError(self.fields['email'].error_message['exists'])
        return self.cleaned_data['email']


class Contact_us(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.email

class Order(models.Model):
    image = models.ImageField(upload_to='ecommerce/order/image')
    product = models.CharField(max_length=1000,default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.CharField(max_length=5)
    total = models.CharField(max_length=1000, default='')
    address = models.TextField()
    phone = models.CharField(max_length=10)
    date = models.DateField(default=datetime.datetime.today)

    def __str__(self):
        return self.product

Shop3T/E_shop/templates/contact.html
{% extends "master.html" %}
{% block body %}
<div id="contact-page" class="container">
    	<div class="bg">
	    	<div class="row">
	    		<div class="col-sm-12">
					<h2 class="title text-center">Contact <strong>Us</strong></h2>
					<div id="gmap" class="contact-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.231171196225!2d106.80086541533015!3d10.870014160430362!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317527587e9ad5bf%3A0xafa66f9c8be3c91!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBDw7RuZyBuZ2jhu4cgVGjDtG5nIHRpbiDEkEhRRyBUUC5IQ00!5e0!3m2!1svi!2s!4v1636287804495!5m2!1svi!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
					</div>
				</div>
			</div>
			<br>
    		<div class="row">
	    		<div class="col-sm-8">
	    			<div class="contact-form">
	    				<h2 class="title text-center">Get In Touch</h2>
	    				<div class="status alert alert-success" style="display: none"></div>
				    	<form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
							{% csrf_token %}
				            <div class="form-group col-md-6">
				                <input type="text" name="name" class="form-control" required="required" placeholder="Name">
				            </div>
				            <div class="form-group col-md-6">
				                <input type="email" name="email" class="form-control" required="required" placeholder="Email">
				            </div>
				            <div class="form-group col-md-12">
				                <input type="text" name="subject" class="form-control" required="required" placeholder="Subject">
				            </div>
				            <div class="form-group col-md-12">
				                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your Message Here"></textarea>
				            </div>
				            <div class="form-group col-md-12">
				                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit">
				            </div>
				        </form>
	    			</div>
	    		</div>
	    		<div class="col-sm-4">
	    			<div class="contact-info">
	    				<h2 class="title text-center">Contact Info</h2>
	    				<address>
	    					<p>3T E-Shopper</p>
							<p>Khu pho 6, P. Linh Trung, Q. Thu Duc</p>
							<p>TP. Ho Chi Minh, Viet Nam</p>
							<p>Mobile: +84 123 456 789</p>
							<p>Fax: 0-123-456-789</p>
							<p>Email: 3t@gmail.com</p>
	    				</address>
	    				<div class="social-networks">
	    					<h2 class="title text-center">Social Networking</h2>
							<ul>
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-google-plus"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-youtube"></i></a>
								</li>
							</ul>
	    				</div>
	    			</div>
    			</div>
	    	</div>
    	</div>
    </div><!--/#contact-page-->

{% endblock %}

Shop3T/E_shop/templates/index.html
{% extends 'master.html' %}
{% block body %}
<div id="carousel" class="carousel slide" data-ride="carousel" style="margin-bottom: 20px;">
	<ol class="carousel-indicators">
			<li data-target="#carousel" data-slide-to="0"></li>
			<li data-target="#carousel" data-slide-to="1"></li>
			<li data-target="#carousel" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
			<div class="item active">
					<img style="width: 92%;"src="../static/images/newfeeds/asus oled 5 ly do theumb.jpg" alt="Slide 1">
			</div>
			<div class="item">
					<img style="width: 92%;"src="../static/images/newfeeds/thumb asus vivo book pro oled.jpg" alt="Slide 2">
			</div>
			<div class="item">
					<img style="width: 92%;"src="../static/images/newfeeds/thumb black friday finnal.jpg" alt="Slide 3">
			</div>
	</div>
	<a href="#carousel" class="left carousel-control" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left"></span>
	</a>
	<a href="#carousel" class="right carousel-control" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right"></span>
	</a>
</div>
<section>
		<div class="container">
			<div class="row">
				<div class="features_items"><!--features_items-->
					<h2 class="title text-center" style="background-color: bisque; padding: 10px 0px;">Mobile</h2>
					{% for prod in product %}
					{% if prod.id == 10 or prod.id == 11 or prod.id == 12 %}
					<div class="col-sm-4">
						<div class="product-image-wrapper">
							<div class="single-products">
									<div class="productinfo text-center">
										<div style="height: 200px;">
											<img src="{{prod.image}}" alt=""  height="150px" style="object-fit: contain;"/>
										</div>
										<h2>${{prod.price}}</h2>
										<p>{{prod.name}}</p>
										<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
									<div class="product-overlay">
										<div class="overlay-content">
											<h2>{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
							</div>
							<div class="choose">
								<ul class="nav nav-pills nav-justified">
									<li><a href="/product/{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>
								</ul>
							</div>
						</div>
					</div>
					{% endif %}
					{% endfor %}
				</div><!--features_items-->
				<div class="features_items"><!--features_items-->
					<h2 class="title text-center" style="background-color: bisque; padding: 10px 0px;">Laptop</h2>
					{% for prod in product %}
					{% if prod.id == 26 or prod.id == 21 or prod.id == 22 %}
					<div class="col-sm-4">
						<div class="product-image-wrapper">
							<div class="single-products">
									<div class="productinfo text-center">
										<div style="height: 200px;">
											<img src="{{prod.image}}" alt=""  height="150px" style="object-fit: contain;"/>
										</div>
										<h2>${{prod.price}}</h2>
										<p>{{prod.name}}</p>
										<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
									<div class="product-overlay">
										<div class="overlay-content">
											<h2>{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
							</div>
							<div class="choose">
								<ul class="nav nav-pills nav-justified">
									<li><a href="/product/{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>
								</ul>
							</div>
						</div>
					</div>
					{% endif %}
					{% endfor %}
				</div><!--features_items-->
				<div class="features_items"><!--features_items-->
					<h2 class="title text-center" style="background-color: bisque; padding: 10px 0px;">Other</h2>
					{% for prod in product %}
					{% if prod.id == 32 or prod.id == 29 or prod.id == 38 %}
					<div class="col-sm-4">
						<div class="product-image-wrapper">
							<div class="single-products">
									<div class="productinfo text-center">
										<div style="height: 200px;">
											<img src="{{prod.image}}" alt=""  height="150px" style="object-fit: contain;"/>
										</div>
										<h2>${{prod.price}}</h2>
										<p>{{prod.name}}</p>
										<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
									<div class="product-overlay">
										<div class="overlay-content">
											<h2>{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
							</div>
							<div class="choose">
								<ul class="nav nav-pills nav-justified">
									<li><a href="/product/{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>
								</ul>
							</div>
						</div>
					</div>
					{% endif %}
					{% endfor %}
				</div><!--features_items-->

				<!-- </div> -->
			</div>
		</div>
	</section>

{% endblock %}

Shop3T/E_shop/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | 3T Shop</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/prettyPhoto.css" rel="stylesheet">
    <link href="/static/css/price-range.css" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
	<link href="/static/css/main.css" rel="stylesheet">
	<link href="/static/css/responsive.css" rel="stylesheet">
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>

    <header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> 012 3456 789</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> 3t@gmail.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<h3>3T E-SHOP</h3>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="/order/"><i class="fa fa-star"></i> Your Order</a></li>
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="/cart/cart-detail/"><i class="fa fa-shopping-cart"></i> Cart <span class="badge badge-secondary">{{request.session.cart|length}}</span></a></li>
								{% if user.is_authenticated %}
								<li><a href="{% url 'logout' %}"><i class="fa fa-lock"></i> Logout</a></li>
								{% else %}
								<<li><a href="{% url 'login' %}"><i class="fa fa-lock"></i> Login</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{% url 'index' %}">Home</a></li>
                  <li><a href="/product/">Products</a></li>
								<li><a href="{% url 'contact_page' %}">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<form method="get" action="/search/">
							<div class="search_box pull-right">
								<input name="query" type="text" placeholder="Search"/>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

{% block body %} {% endblock %}


    <footer id="footer"><!--Footer-->

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quick Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Laptop</a></li>
								<li><a href="#">Mobile</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shop</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © of Group 3T</p>
					<p class="pull-right">Bui Xuan Thai - Nguyen Minh Tri - Nguyen Thanh Tien</p>
				</div>
			</div>
		</div>

	</footer><!--/Footer-->


    <script src="/static/js/jquery.js"></script>
	<script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/jquery.scrollUp.min.js"></script>
	<script src="/static/js/price-range.js"></script>
    <script src="/static/js/jquery.prettyPhoto.js"></script>
    <script src="/static/js/main.js"></script>
</body>
</html>

Shop3T/E_shop/templates/order.html
{% extends 'master.html' %}
{% block body %}
	<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Your Order</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
					{% for i in order %}
						<tr>
							<td class="cart_product">
								<a href=""><img width="150px" height="200px" src="{{i.image}}" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{i.product}}</a></h4>

							</td>
							<td class="cart_price">
								<p>${{i.price}}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<p>{{i.quantity}}</p>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">${{i.total}}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>
						{% endfor %}

					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

{% endblock %}

Shop3T/E_shop/templates/product.html
{% extends 'master.html' %}
{% block body %}
<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->

							{% for cat in category %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all %}
											<li><a href="/product/?category={{i.id}}">{{i.name}}</a></li>
											{% endfor %}

										</ul>
									</div>
								</div>
							</div>
							{% endfor %}

						</div><!--/category-productsr-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/?brand={{i.id}}">{{i.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->


						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>

						{% for prod in product %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<div style="height: 200px;">
											<img src="/{{prod.image}}" alt=""  height="200px;" style="object-fit: contain;"/>
											</div>
											<h2>${{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
										</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>

									</ul>
								</div>
							</div>
						</div>
						{% endfor %}

						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>

{% endblock %}

Shop3T/E_shop/templates/search.html
{% extends 'master.html' %}
{% block body %}
	<div class="container">

	<div class="features_items"><!--features_items-->
		<h2 class="title text-center">Search Result:</h2>
		{% if product|length < 1 %}
			<div class="content-404">
				<img src="images/404/404.png" class="img-responsive" alt="" />
				<h1><b>OPPS!</b> We Couldn’t Find This Product</h1>
				<p>Uh... So it looks like you brock something. The page you are looking for has up and Vanished.</p>
				<h2><a href="{% url 'index' %}">Bring me back Home</a></h2>
			</div>
		{% endif %}

		{% for prod in product %}
		<div class="col-sm-4">
			<div class="product-image-wrapper">
				<div class="single-products">
						<div class="productinfo text-center">
							<img src="/{{prod.image}}" alt=""  height="200px;"/>
							<h2>${{prod.price}}</h2>
							<p>{{prod.name}}</p>
							<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
						</div>
						<div class="product-overlay">
							<div class="overlay-content">
								<h2>{{prod.price}}</h2>
								<p>{{prod.name}}</p>
								<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
							</div>
						</div>
				</div>
			</div>
		</div>
		{% endfor %}
		
	</div><!--features_items-->
</div>
{% endblock %}